"""Orbot is not started screen."""
s0 = {
    "hierarchy": {
        "@rotation": "0",
        "node": [
            {
                "@bounds": "[0,0][720,1280]",
                "@checkable": "false",
                "@checked": "false",
                "@class": "android.widget.FrameLayout",
                "@clickable": "false",
                "@content-desc": "",
                "@enabled": "true",
                "@focusable": "false",
                "@focused": "false",
                "@index": "0",
                "@long-clickable": "false",
                "@package": "org.torproject.android",
                "@password": "false",
                "@resource-id": "",
                "@scrollable": "false",
                "@selected": "false",
                "@text": "",
                "@visible-to-user": "true",
                "node": [
                    {
                        "@bounds": "[32,77][133,131]",
                        "@checkable": "false",
                        "@checked": "false",
                        "@class": "android.widget.TextView",
                        "@clickable": "false",
                        "@content-desc": "",
                        "@enabled": "true",
                        "@focusable": "false",
                        "@focused": "false",
                        "@index": "0",
                        "@long-clickable": "false",
                        "@package": "org.torproject.android",
                        "@password": "false",
                        "@resource-id": "",
                        "@scrollable": "false",
                        "@selected": "false",
                        "@text": "Orbot",
                        "@visible-to-user": "true",
                    },
                    {
                        "@bounds": "[544,56][640,152]",
                        "@checkable": "false",
                        "@checked": "false",
                        "@class": "android.widget.TextView",
                        "@clickable": "true",
                        "@content-desc": "New Identity",
                        "@enabled": "true",
                        "@focusable": "true",
                        "@focused": "false",
                        "@index": "1",
                        "@long-clickable": "false",
                        "@package": "org.torproject.android",
                        "@password": "false",
                        "@resource-id": "org.torproject.android:id/menu_newnym",
                        "@scrollable": "false",
                        "@selected": "false",
                        "@text": "",
                        "@visible-to-user": "true",
                    },
                    {
                        "@bounds": "[640,56][720,152]",
                        "@checkable": "false",
                        "@checked": "false",
                        "@class": "android.widget.ImageView",
                        "@clickable": "true",
                        "@content-desc": "\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200f\u200f\u200e\u200f\u200f\u200f\u200f\u200f\u200f\u200f\u200e\u200e\u200e\u200f\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200f\u200f\u200e\u200f\u200f\u200f\u200e\u200f\u200e\u200e\u200f\u200e\u200e\u200f\u200f\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200e\u200f\u200e\u200f\u200e\u200eMore "
                        "options\u200e\u200f\u200e\u200e\u200f\u200e",
                        "@enabled": "true",
                        "@focusable": "true",
                        "@focused": "false",
                        "@index": "2",
                        "@long-clickable": "true",
                        "@package": "org.torproject.android",
                        "@password": "false",
                        "@resource-id": "",
                        "@scrollable": "false",
                        "@selected": "false",
                        "@text": "",
                        "@visible-to-user": "true",
                    },
                    {
                        "@bounds": "[0,160][720,1280]",
                        "@checkable": "false",
                        "@checked": "false",
                        "@class": "androidx.drawerlayout.widget.DrawerLayout",
                        "@clickable": "false",
                        "@content-desc": "",
                        "@enabled": "true",
                        "@focusable": "false",
                        "@focused": "false",
                        "@index": "3",
                        "@long-clickable": "false",
                        "@package": "org.torproject.android",
                        "@password": "false",
                        "@resource-id": "org.torproject.android:id/drawer_layout",
                        "@scrollable": "false",
                        "@selected": "false",
                        "@text": "",
                        "@visible-to-user": "true",
                        "node": {
                            "@bounds": "[0,160][720,1280]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ScrollView",
                            "@clickable": "false",
                            "@content-desc": "",
                            "@enabled": "true",
                            "@focusable": "true",
                            "@focused": "false",
                            "@index": "0",
                            "@long-clickable": "false",
                            "@package": "org.torproject.android",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "true",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                            "node": [
                                {
                                    "@bounds": "[6,182][714,632]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.ImageView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "0",
                                    "@long-clickable": "true",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/imgStatus",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[272,384][448,480]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.Button",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "1",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/btnStart",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "START",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[0,668][720,706]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "2",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/lblStatus",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Tor v0.4.7.10",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[24,730][696,768]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "3",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/lblPorts",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[15,816][345,871]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.Spinner",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "4",
                                    "@long-clickable": "true",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/spinnerCountry",
                                    "@scrollable": "true",
                                    "@selected": "false",
                                    "@text": "",
                                    "@visible-to-user": "true",
                                    "node": {
                                        "@bounds": "[21,822][339,865]",
                                        "@checkable": "false",
                                        "@checked": "false",
                                        "@class": "android.widget.TextView",
                                        "@clickable": "false",
                                        "@content-desc": "",
                                        "@enabled": "true",
                                        "@focusable": "false",
                                        "@focused": "false",
                                        "@index": "0",
                                        "@long-clickable": "false",
                                        "@package": "org.torproject.android",
                                        "@password": "false",
                                        "@resource-id": "android:id/text1",
                                        "@scrollable": "false",
                                        "@selected": "false",
                                        "@text": "Global " "(Auto)",
                                        "@visible-to-user": "true",
                                    },
                                },
                                {
                                    "@bounds": "[423,816][657,870]",
                                    "@checkable": "true",
                                    "@checked": "true",
                                    "@class": "android.widget.Switch",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "5",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/btnVPN",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "VPN Mode "
                                    "\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200f\u200e\u200e\u200f\u200f\u200e\u200e\u200e\u200f\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200f\u200e\u200e\u200f\u200f\u200e\u200f\u200f\u200e\u200e\u200e\u200eON\u200e\u200f\u200e\u200e\u200f\u200e",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[117,916][242,954]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "6",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Download",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[98,966][262,1004]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "7",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/trafficDown",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "0KiB/s / 0KiB",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[496,916][584,954]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "8",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Upload",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[458,966][622,1004]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "9",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/trafficUp",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "0KiB/s / 0KiB",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[107,1036][353,1074]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "10",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Trouble " "connecting?",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[365,1028][613,1082]",
                                    "@checkable": "true",
                                    "@checked": "false",
                                    "@class": "android.widget.Switch",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "11",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/btnBridges",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Use Bridges "
                                    "\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200f\u200e\u200e\u200e\u200e\u200f\u200f\u200f\u200f\u200f\u200f\u200e\u200f\u200f\u200f\u200e\u200f\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200f\u200e\u200e\u200e\u200f\u200f\u200f\u200e\u200f\u200f\u200e\u200e\u200f\u200f\u200e\u200f\u200f\u200e\u200f\u200e\u200e\u200e\u200e\u200e\u200f\u200f\u200e\u200f\u200e\u200f\u200f\u200e\u200f\u200f\u200f\u200e\u200e\u200f\u200e\u200e\u200f\u200f\u200e\u200e\u200f\u200f\u200f\u200e\u200f\u200f\u200eOFF\u200e\u200f\u200e\u200e\u200f\u200e",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[251,1120][469,1158]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.TextView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "false",
                                    "@focused": "false",
                                    "@index": "12",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "Tor-Enabled " "Apps",
                                    "@visible-to-user": "true",
                                },
                                {
                                    "@bounds": "[180,1176][480,1262]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.HorizontalScrollView",
                                    "@clickable": "false",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "13",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/llBoxShortcuts",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "",
                                    "@visible-to-user": "true",
                                    "node": [
                                        {
                                            "@NAF": "true",
                                            "@bounds": "[183,1179][327,1259]",
                                            "@checkable": "false",
                                            "@checked": "false",
                                            "@class": "android.widget.ImageView",
                                            "@clickable": "true",
                                            "@content-desc": "",
                                            "@enabled": "true",
                                            "@focusable": "true",
                                            "@focused": "false",
                                            "@index": "0",
                                            "@long-clickable": "false",
                                            "@package": "org.torproject.android",
                                            "@password": "false",
                                            "@resource-id": "",
                                            "@scrollable": "false",
                                            "@selected": "false",
                                            "@text": "",
                                            "@visible-to-user": "true",
                                        },
                                        {
                                            "@NAF": "true",
                                            "@bounds": "[333,1179][477,1259]",
                                            "@checkable": "false",
                                            "@checked": "false",
                                            "@class": "android.widget.ImageView",
                                            "@clickable": "true",
                                            "@content-desc": "",
                                            "@enabled": "true",
                                            "@focusable": "true",
                                            "@focused": "false",
                                            "@index": "1",
                                            "@long-clickable": "false",
                                            "@package": "org.torproject.android",
                                            "@password": "false",
                                            "@resource-id": "",
                                            "@scrollable": "false",
                                            "@selected": "false",
                                            "@text": "",
                                            "@visible-to-user": "true",
                                        },
                                    ],
                                },
                                {
                                    "@NAF": "true",
                                    "@bounds": "[492,1195][540,1243]",
                                    "@checkable": "false",
                                    "@checked": "false",
                                    "@class": "android.widget.ImageView",
                                    "@clickable": "true",
                                    "@content-desc": "",
                                    "@enabled": "true",
                                    "@focusable": "true",
                                    "@focused": "false",
                                    "@index": "14",
                                    "@long-clickable": "false",
                                    "@package": "org.torproject.android",
                                    "@password": "false",
                                    "@resource-id": "org.torproject.android:id/ivAppVpnSettings",
                                    "@scrollable": "false",
                                    "@selected": "false",
                                    "@text": "",
                                    "@visible-to-user": "true",
                                },
                            ],
                        },
                    },
                ],
            },
            {
                "@bounds": "[0,0][720,48]",
                "@checkable": "false",
                "@checked": "false",
                "@class": "android.widget.FrameLayout",
                "@clickable": "false",
                "@content-desc": "",
                "@enabled": "true",
                "@focusable": "false",
                "@focused": "false",
                "@index": "0",
                "@long-clickable": "false",
                "@package": "com.android.systemui",
                "@password": "false",
                "@resource-id": "",
                "@scrollable": "false",
                "@selected": "false",
                "@text": "",
                "@visible-to-user": "true",
                "node": {
                    "@bounds": "[0,0][720,48]",
                    "@checkable": "false",
                    "@checked": "false",
                    "@class": "android.widget.FrameLayout",
                    "@clickable": "false",
                    "@content-desc": "",
                    "@enabled": "true",
                    "@focusable": "false",
                    "@focused": "false",
                    "@index": "0",
                    "@long-clickable": "false",
                    "@package": "com.android.systemui",
                    "@password": "false",
                    "@resource-id": "com.android.systemui:id/status_bar",
                    "@scrollable": "false",
                    "@selected": "false",
                    "@text": "",
                    "@visible-to-user": "true",
                    "node": [
                        {
                            "@bounds": "[32,0][101,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.TextView",
                            "@clickable": "false",
                            "@content-desc": "5:12 PM",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "0",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "com.android.systemui:id/clock",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "5:12",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[101,0][145,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ImageView",
                            "@clickable": "false",
                            "@content-desc": "Apps "
                            "notification: 2 "
                            "app updates are "
                            "available",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "1",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[145,0][189,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ImageView",
                            "@clickable": "false",
                            "@content-desc": "Orbot "
                            "notification: "
                            "Orbot is "
                            "Deactivated",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "2",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[189,0][233,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ImageView",
                            "@clickable": "false",
                            "@content-desc": "Android System "
                            "notification: "
                            "USB debugging "
                            "connected",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "3",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[233,0][277,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ImageView",
                            "@clickable": "false",
                            "@content-desc": "F-Droid "
                            "notification: 2 "
                            "Updates",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "4",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[602,2][660,46]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.ImageView",
                            "@clickable": "false",
                            "@content-desc": "Ringer vibrate.",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "5",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                        {
                            "@bounds": "[672,0][688,48]",
                            "@checkable": "false",
                            "@checked": "false",
                            "@class": "android.widget.LinearLayout",
                            "@clickable": "false",
                            "@content-desc": "Battery "
                            "charging, 100 "
                            "percent.",
                            "@enabled": "true",
                            "@focusable": "false",
                            "@focused": "false",
                            "@index": "6",
                            "@long-clickable": "false",
                            "@package": "com.android.systemui",
                            "@password": "false",
                            "@resource-id": "com.android.systemui:id/battery",
                            "@scrollable": "false",
                            "@selected": "false",
                            "@text": "",
                            "@visible-to-user": "true",
                        },
                    ],
                },
            },
        ],
    }
}
